### ISSUE TITLE
reset event question

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet#193]
I'm trying to solve a problem relating to puppet not reseting correctly.
While I was reading the puppet code, i cannot find the part binding reset event to ServiceCtlMixin.reset(). Since puppet emitting reset event cannot trigger reset in my case, is there something I miss?

**Comment by huan** [comment]
During the past we have changed the reset specification many times.

I’m not sure the current mechanism, so please help yourself to figure it out.

One tip is that I feel the RESET event should not pass across puppet layers, it should be a local and private event for the current puppet only.

**Comment by hcfw007** [comment]
OK. Maybe this is a better question:
As a puppet implementation developer, should I pass the reset event up, or handle it at puppet implementation layer?

**Comment by huan** [comment]
> As a puppet implementation developer, should I pass the reset event up, or handle it at puppet implementation layer?

The RESET event is to reset the current system instead of resetting other system. so, for now, let's follow the below two rules:

1. the RESET event should be a local/internal/private event for the current puppet
2. a puppet can ignore the RESET event that does not emit by itself for now

Please feel free if you can find any use cases that need to break the above two rules.

**Comment by hcfw007** [comment]
I understand the design now so issue can be closed.

**Comment by huan** [comment]
Glad to know that you understood the design, it would better to share what you have learned so that the future developers can learn from you.

And thank you very much for the house cleaning!
